version: '2'
services:

  ##########################
  ### GIFTS FRONTEND #######
  ##########################

  fe_gifts:
    build:
      context: ./frontend-gifts
    environment:
      VIRTUAL_HOST: gifts.cw2.local
    ports:
     - "3000:3000"
    volumes:
     - ./frontend-gifts:/app
     - /app/node_modules

  ##########################
  ### GIFTS BACKEND ########
  ##########################

  be_gifts:
    image: wodby/drupal-php:7.1
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG_ENABLED: 1
      # PHP_XDEBUG_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./backend-gifts:/var/www/html
      # - d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  be_gifts_mariadb:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  be_gifts_nginx:
    image: wodby/drupal-nginx:1.10-1.1.0
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: be_gifts
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
      VIRTUAL_HOST: gifts.api.cw2.local
    volumes_from:
      - be_gifts

  be_gifts_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_gifts_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"


  ##########################
  ### DONATIONS BACKEND ####
  ##########################

  be_donations:
    image: wodby/drupal-php:7.1
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG_ENABLED: 1
      # PHP_XDEBUG_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./backend-donations:/var/www/html
      #- d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  be_donations_mariadb:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  be_donations_nginx:
    image: wodby/drupal-nginx:1.10-1.1.0
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: be_donations
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
      VIRTUAL_HOST: donations.api.cw2.local
    volumes_from:
      - be_donations

  be_donations_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_donations_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8002:80"


  ##########################
  ### NGINX PROXY ##########
  ##########################

  nginx-proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
